"""Declared semantic operator families and projections for the video adapter.

Family assignments preserve the existing supported inventory; they are not a
claim that every external algorithm is locally implemented. Unknown identities
require an explicit declaration, never inference from words in their names.
"""

from .registry_evidence import EXECUTION_MANIFEST_REF

ALGORITHM_FAMILIES = {
    "ABSOLUTE_FINAL_AV_DRIFT_DOES_NOT_EXCEED_ONE_FRAME": "ORDERED_NUMERIC_PREDICATE_V1",
    "ABSOLUTE_FINAL_AV_DRIFT_EQUALS_ABS_FINAL_AV_DRIFT": "CANONICAL_VALUE_OR_SET_EQUALITY_V1",
    "ALIGNMENT_RECEIPT_AUDIO_SHA256_EQUALS_AUDIO_SHA256": "HASH_AND_BYTE_LINEAGE_V1",
    "ALIGNMENT_RECEIPT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "ASSET_MANIFEST_SHA256_MATCHES_CANONICAL_ASSET_ARRAY": "HASH_AND_BYTE_LINEAGE_V1",
    "ASSET_PLAN_SHA256_MATCHES_REFERENCED_ASSET_PLAN": "HASH_AND_BYTE_LINEAGE_V1",
    "ASSET_PROVENANCE_REFS_AND_HASHES_HAVE_EQUAL_CARDINALITY": "EXACT_ARRAY_CARDINALITY_COMPARISON_V1",
    "ASSET_SEMANTIC_BINDINGS_RESOLVE_TO_NARRATION_AND_CLAIM_MATRIX": "DECLARED_DEPENDENCY_RELATION_V1",
    "AUDIO_SHA256_MATCHES_REFERENCED_AUDIO_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "AUTHORING_FIELDS_DESCRIBE_THE_IMMUTABLE_CANDIDATE_HANDOFF_NOT_CURRENT_RUNTIME_STATE": "EXACT_NAMED_PREDICATE_V1",
    "AUTHORIZED_ENVIRONMENT_MANIFEST_SHA256_EQUALS_CURRENT_ENVIRONMENT_MANIFEST_SHA256": "HASH_AND_BYTE_LINEAGE_V1",
    "AUTHORIZED_OUTPUT_MANIFEST_SHA256_EQUALS_CURRENT_OUTPUT_MANIFEST_SHA256": "HASH_AND_BYTE_LINEAGE_V1",
    "AUTHORIZED_TARGET_EXECUTION_BINDS_EXACT_JOB_COMMIT_INPUT_ENVIRONMENT_AND_OUTPUT": "DECLARED_DEPENDENCY_RELATION_V1",
    "AUTHORIZED_TARGET_SKILL_RUN_REQUIRES_CURRENT_EXACT_AUTHORIZATION_AND_RECEIPT": "DECLARED_DEPENDENCY_RELATION_V1",
    "BEFORE_AND_AFTER_HASHES_MATCH_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "CASE_MANIFEST_HASHES_MATCH_REFERENCED_CANDIDATE_CASE_DOCUMENTS": "HASH_AND_BYTE_LINEAGE_V1",
    "CLAIM_COVERAGE_SHA256_MATCHES_NARRATION_SCRIPT": "HASH_AND_BYTE_LINEAGE_V1",
    "CLAIM_IDS_ARE_UNIQUE": "CANONICAL_MEMBER_UNIQUENESS_V1",
    "CLAIM_MANIFEST_SHA256_MATCHES_CANONICAL_CLAIM_ARRAY": "HASH_AND_BYTE_LINEAGE_V1",
    "CLAIM_MATRIX_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "CODEX_IMAGEGEN_MATERIALIZATION_REQUIRES_SEPARATE_CURRENT_AUTHORIZATION": "DECLARED_DEPENDENCY_RELATION_V1",
    "COMPLETED_SIDE_EFFECTS_AND_IDEMPOTENCY_KEYS_ARE_NOT_REPLAYED": "POLICY_STATE_PREDICATE_V1",
    "DEMO_CLAIM_IDS_RESOLVE_TO_SAME_JOB_CLAIM_MATRIX": "DECLARED_DEPENDENCY_RELATION_V1",
    "DEMO_CONTRACT_REF_RESOLVES_TO_SAME_JOB_BEFORE_AFTER_CONTRACT": "DECLARED_DEPENDENCY_RELATION_V1",
    "DEMO_EFFECT_CLAIM_RESOLVES_TO_SAME_JOB_CLAIM_MATRIX": "DECLARED_DEPENDENCY_RELATION_V1",
    "DEMO_EFFECT_DELTA_BEFORE_AND_AFTER_VALUES_ARE_DISTINCT": "EXACT_NAMED_PREDICATE_V1",
    "DEMO_EFFECT_DELTA_CONTAINS_OBSERVED_STATE_CHANGE": "EXACT_NAMED_PREDICATE_V1",
    "DEMO_EFFECT_DELTA_EVIDENCE_BINDS_BEFORE_AND_AFTER_BYTES": "DECLARED_DEPENDENCY_RELATION_V1",
    "DEMO_EFFECT_DELTA_EVIDENCE_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "DEMO_EFFECT_DELTA_PROPERTY_PATHS_RESOLVE_IN_BOTH_STATES": "DECLARED_DEPENDENCY_RELATION_V1",
    "DEMO_EFFECT_DELTA_VALUES_EQUAL_RESOLVED_STATE_VALUES": "DECLARED_DEPENDENCY_RELATION_V1",
    "DEMO_INPUT_AND_OUTPUT_BYTES_ARE_DISTINCT": "EXACT_NAMED_PREDICATE_V1",
    "DEMO_PROCESSING_ACTION_MATCHES_EFFECT_CLAIM": "CANONICAL_VALUE_OR_SET_EQUALITY_V1",
    "DENIED_TARGET_SKILL_GATE_HAS_NO_AUTHORIZATION_OR_SIDE_EFFECT_ATTEMPT": "EXACT_NAMED_PREDICATE_V1",
    "DEPENDENCY_MANIFEST_BINDS_EXACT_DECLARED_ARTIFACT_DEPENDENCIES": "DECLARED_DEPENDENCY_RELATION_V1",
    "DEPENDENCY_MANIFEST_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "EACH_DECLARED_OBJECT_HAS_NONZERO_PROBED_MOTION": "ORDERED_NUMERIC_PREDICATE_V1",
    "ENTER_HOLD_EXIT_SEGMENTS_ARE_CONTIGUOUS_AND_MATCH_DECLARED_INTERVALS": "ORDERED_NUMERIC_PREDICATE_V1",
    "ENTER_TIME_LESS_THAN_OR_EQUAL_TO_HOLD_START": "ORDERED_NUMERIC_PREDICATE_V1",
    "EVENT_HASH_RECOMPUTES_FROM_PREVIOUS_HASH_AND_CANONICAL_EVENT_PAYLOAD": "HASH_AND_BYTE_LINEAGE_V1",
    "EVENT_PAYLOAD_SHA256_MATCHES_CANONICAL_STAGE_EVENT": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_ACCEPTANCE_CASE_RESULT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_ASSET_BINDS_SENTENCES_CLAIMS_AND_VISUAL_INTENT": "DECLARED_DEPENDENCY_RELATION_V1",
    "EVERY_ASSET_PROVENANCE_HASH_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_CLAIM_BINDING_RESOLVES_TO_FROZEN_FILE_AND_MATCHES_HASH": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_CLAIM_HAS_FUNCTION_SCENARIO_EFFECT_AND_SOURCE_EVIDENCE": "EXACT_NAMED_PREDICATE_V1",
    "EVERY_FIXTURE_CASE_RESULT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_FIXTURE_VIDEO_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_FROZEN_FILE_HASH_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_INVARIANT_MUTATION_PRESERVES_JSON_SCHEMA_AND_FAILS_DECLARED_INVARIANT": "EXACT_NAMED_PREDICATE_V1",
    "EVERY_INVARIANT_NEGATIVE_RESULT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_MATERIALIZED_ASSET_REF_HASH_MATCHES_ASSET_SHA256": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_MOTION_OBJECT_BINDS_SENTENCES_CLAIMS_VISUAL_INTENT_ASSET_AND_AUDIO_ANCHOR": "DECLARED_DEPENDENCY_RELATION_V1",
    "EVERY_MOTION_SEGMENT_HAS_DISTINCT_FROM_AND_TO_STATE": "EXACT_NAMED_PREDICATE_V1",
    "EVERY_NEGATIVE_CASE_RESULT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_NEGATIVE_MUTATION_VARIANT_HAS_HASH_BOUND_EXECUTION_EVIDENCE": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_NEGATIVE_RESULT_OBSERVES_EXPECTED_FAILURE_WITHOUT_SIDE_EFFECTS": "EXACT_NAMED_PREDICATE_V1",
    "EVERY_OBJECT_AUDIO_ANCHOR_ID_EXISTS_IN_AUDIO_ANCHOR_IDS": "DECLARED_DEPENDENCY_RELATION_V1",
    "EVERY_OBJECT_MOTION_PROBE_HASH_MATCHES_REFERENCED_PROBE": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_OBJECT_WORD_TO_MOTION_ERROR_DOES_NOT_EXCEED_0_1_SECONDS": "ORDERED_NUMERIC_PREDICATE_V1",
    "EVERY_SCHEMA_NATIVE_MUTATION_FAILS_SCHEMA_WITHOUT_ORACLE_OR_SIDE_EFFECTS": "EXACT_NAMED_PREDICATE_V1",
    "EVERY_SCHEMA_NATIVE_RESULT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_SENTENCE_HAS_A_VISUAL_INTENT": "EXACT_NAMED_PREDICATE_V1",
    "EVERY_SPOKEN_SENTENCE_HAS_VISIBLE_OBJECT_DURING_BOUND_AUDIO_ANCHOR": "EXACT_NAMED_PREDICATE_V1",
    "EVERY_VERIFIED_CLAIM_IS_COVERED_BY_AT_LEAST_ONE_SENTENCE": "EXACT_NAMED_PREDICATE_V1",
    "EVERY_WORD_ANCHOR_AUDIO_SHA256_EQUALS_TOP_LEVEL_AUDIO_SHA256": "HASH_AND_BYTE_LINEAGE_V1",
    "EVERY_WORD_ANCHOR_START_SECONDS_IS_LESS_THAN_END_SECONDS": "ORDERED_NUMERIC_PREDICATE_V1",
    "EXPECTED_FUNCTION_SCENARIO_EFFECT_RESOLVE_TO_JOB_CLAIM_MATRIX": "DECLARED_DEPENDENCY_RELATION_V1",
    "FFPROBE_INPUT_SHA256_EQUALS_VIDEO_SHA256": "HASH_AND_BYTE_LINEAGE_V1",
    "FFPROBE_RECEIPT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "FINAL_SHOT_END_EQUALS_DURATION_SECONDS": "CANONICAL_VALUE_OR_SET_EQUALITY_V1",
    "FIRST_SHOT_STARTS_AT_ZERO": "EXACT_NAMED_PREDICATE_V1",
    "FROZEN_FILE_REFS_AND_HASHES_HAVE_EQUAL_CARDINALITY": "EXACT_ARRAY_CARDINALITY_COMPARISON_V1",
    "FULL_TIMELINE_CONTIGUOUS_NO_GAPS_OR_OVERLAPS": "ORDERED_NUMERIC_PREDICATE_V1",
    "HOLD_END_LESS_THAN_OR_EQUAL_TO_EXIT_TIME": "ORDERED_NUMERIC_PREDICATE_V1",
    "HOLD_START_LESS_THAN_HOLD_END": "ORDERED_NUMERIC_PREDICATE_V1",
    "HUMAN_REVIEW_CLOSURE_HASH_MATCHES_REFERENCED_CLOSURE_RECEIPT": "HASH_AND_BYTE_LINEAGE_V1",
    "ILLUSTRATION_IS_EXPLICITLY_LABELED_AND_NOT_ACTUAL_SKILL_OUTPUT": "EXACT_NAMED_PREDICATE_V1",
    "IMAGEGEN_RECEIPT_HASH_MATCHES_REFERENCED_BYTES_WHEN_MATERIALIZED": "HASH_AND_BYTE_LINEAGE_V1",
    "INPUT_MANIFEST_SHA256_MATCHES_CANONICAL_INPUT_HASHES": "HASH_AND_BYTE_LINEAGE_V1",
    "LICENSE_SPDX_MATCHES_HASHED_LICENSE_EVIDENCE": "HASH_AND_BYTE_LINEAGE_V1",
    "LICENSE_SPDX_MATCHES_TTS_MODEL_LICENSE_EVIDENCE": "CANONICAL_VALUE_OR_SET_EQUALITY_V1",
    "LOCAL_DETERMINISTIC_ASSET_RECIPE_AND_OUTPUT_ARE_HASH_BOUND": "HASH_AND_BYTE_LINEAGE_V1",
    "LOCAL_RENDER_ALIGNMENT_RECEIPT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "LOCAL_RENDER_TTS_RECEIPT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "MEDIA_ALIGNMENT_RECEIPT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "MEDIA_RENDER_RECEIPT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "MEDIA_TTS_RECEIPT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "MOTION_IR_SHA256_MATCHES_REFERENCED_MOTION_IR": "HASH_AND_BYTE_LINEAGE_V1",
    "MOTION_OBJECT_BINDINGS_RESOLVE_TO_NARRATION_ASSET_AND_ALIGNMENT": "DECLARED_DEPENDENCY_RELATION_V1",
    "MOTION_PROBE_BINDS_FINAL_VIDEO_SHA256_AND_MOTION_IR_SHA256": "HASH_AND_BYTE_LINEAGE_V1",
    "MOTION_PROBE_SHA256_MATCHES_REFERENCED_PROBE": "HASH_AND_BYTE_LINEAGE_V1",
    "MOTION_SEGMENT_IDS_ARE_UNIQUE": "CANONICAL_MEMBER_UNIQUENESS_V1",
    "NARRATION_BUDGET_ESTIMATE_MATCHES_CANONICAL_SENTENCE_ARRAY_AND_METHOD": "CANONICAL_VALUE_OR_SET_EQUALITY_V1",
    "NARRATION_BUDGET_RECEIPT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "NARRATION_SCRIPT_SHA256_MATCHES_REFERENCED_SCRIPT": "HASH_AND_BYTE_LINEAGE_V1",
    "NARRATION_VISUAL_INTENT_IDS_ARE_UNIQUE": "CANONICAL_MEMBER_UNIQUENESS_V1",
    "NEGATIVE_MUTATION_MANIFEST_HASH_MATCHES_REFERENCED_VARIANTS": "HASH_AND_BYTE_LINEAGE_V1",
    "OBSERVED_DYNAMIC_FRAME_COUNT_IS_NONZERO": "ORDERED_NUMERIC_PREDICATE_V1",
    "OBSERVED_MOTION_SEMANTIC_BINDINGS_EQUAL_RENDERED_AND_MOTION_BINDINGS": "CANONICAL_VALUE_OR_SET_EQUALITY_V1",
    "OBSERVED_REPO_FIXTURE_REQUIRES_PINNED_SOURCE_EVIDENCE": "DECLARED_DEPENDENCY_RELATION_V1",
    "OBSERVED_SCENE_TRANSITION_COUNT_EQUALS_EXPECTED_SCENE_TRANSITION_COUNT": "CANONICAL_VALUE_OR_SET_EQUALITY_V1",
    "ORACLE_EVALUATOR_REGISTRY_HASH_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "OUTPUT_MANIFEST_SHA256_MATCHES_CANONICAL_OUTPUT_HASHES": "HASH_AND_BYTE_LINEAGE_V1",
    "PREVIOUS_STAGE_ID_MATCHES_FROZEN_STAGE_ORDER": "CANONICAL_VALUE_OR_SET_EQUALITY_V1",
    "PROVIDER_RECEIPT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "RECOMPUTED_ANCHOR_ERROR_DOES_NOT_EXCEED_0_1_SECONDS": "ORDERED_NUMERIC_PREDICATE_V1",
    "RENDERED_SEMANTIC_BINDINGS_EQUAL_MOTION_IR_OBJECT_BINDINGS": "CANONICAL_VALUE_OR_SET_EQUALITY_V1",
    "RENDER_COMMAND_RECEIPT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "RENDER_COMPOSITION_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "RENDER_INPUT_MANIFEST_BINDS_EXACT_ASSET_REFS_AND_SHA256S": "HASH_AND_BYTE_LINEAGE_V1",
    "RENDER_INPUT_MANIFEST_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "RENDER_RECEIPT_VIDEO_SHA256_EQUALS_VIDEO_SHA256": "HASH_AND_BYTE_LINEAGE_V1",
    "RENDER_TRACE_SAMPLES_MATCH_DECLARED_OBJECT_CURVES": "EXACT_NAMED_PREDICATE_V1",
    "RENDER_TRACE_SHA256_MATCHES_REFERENCED_TRACE": "HASH_AND_BYTE_LINEAGE_V1",
    "RENDER_TTS_ALIGNMENT_AND_MEDIA_AUDIO_SHA256_ARE_EQUAL": "HASH_AND_BYTE_LINEAGE_V1",
    "RERUN_INVALIDATED_STAGE_REQUIRES_CHANGED_OR_INVALIDATED_INPUT": "DECLARED_DEPENDENCY_RELATION_V1",
    "REUSE_VALID_RECEIPT_REQUIRES_EXACT_CURRENT_INPUT_HASHES": "HASH_AND_BYTE_LINEAGE_V1",
    "SCENE_TRANSITION_COUNT_EQUALS_NON_INITIAL_TRANSITIONS": "CANONICAL_VALUE_OR_SET_EQUALITY_V1",
    "SCRIPT_SHA256_MATCHES_CANONICAL_SENTENCE_ARRAY": "HASH_AND_BYTE_LINEAGE_V1",
    "SOURCE_EVIDENCE_REFS_AND_HASHES_HAVE_EQUAL_CARDINALITY": "EXACT_ARRAY_CARDINALITY_COMPARISON_V1",
    "SOURCE_MANIFEST_ENTRY_MATCHES_REPOSITORY_COMMIT_AND_TREE": "CANONICAL_VALUE_OR_SET_EQUALITY_V1",
    "STAGE_ID_AND_INDEX_MATCH_FROZEN_STAGE_EXPECTATION": "EXACT_NAMED_PREDICATE_V1",
    "STOP_FOR_AUTHORITY_HAS_NO_SIDE_EFFECT_ATTEMPT": "POLICY_STATE_PREDICATE_V1",
    "TARGET_EXECUTION_AUTHORIZATION_IS_CURRENT_SINGLE_USE_AND_NOT_PROGRAM_WIDE": "EXACT_NAMED_PREDICATE_V1",
    "TARGET_EXECUTION_ENVIRONMENT_RECEIPT_HASH_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "TARGET_EXECUTION_OUTPUT_RECEIPT_HASH_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "TARGET_EXECUTION_RECEIPT_HASH_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "TRANSCRIPT_SHA256_MATCHES_SYNTHESIZED_AUDIO_TRANSCRIPT": "HASH_AND_BYTE_LINEAGE_V1",
    "TTS_ALIGNMENT_MOTION_AND_RENDER_AUDIO_SHA256_ARE_EQUAL": "HASH_AND_BYTE_LINEAGE_V1",
    "TTS_EXECUTION_MODE_IS_LOCAL_OFFLINE": "EXACT_NAMED_PREDICATE_V1",
    "TTS_MODEL_SHA256_MATCHES_REFERENCED_LOCAL_MODEL_ARTIFACT": "HASH_AND_BYTE_LINEAGE_V1",
    "TTS_NETWORK_ACCESS_WAS_NOT_USED": "POLICY_STATE_PREDICATE_V1",
    "TTS_PROVIDER_IMPLEMENTATION_SHA256_MATCHES_REFERENCED_LOCAL_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "TTS_RECEIPT_AUDIO_SHA256_EQUALS_AUDIO_SHA256": "HASH_AND_BYTE_LINEAGE_V1",
    "TTS_RECEIPT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "TTS_RUNTIME_ENVIRONMENT_SHA256_MATCHES_REFERENCED_BYTES": "HASH_AND_BYTE_LINEAGE_V1",
    "TTS_VOICE_IS_NOT_CLONED": "POLICY_STATE_PREDICATE_V1",
    "VIDEO_BYTES_INCLUDE_THE_REFERENCED_AUDIO_STREAM": "EXACT_NAMED_PREDICATE_V1",
    "WORD_ANCHORS_ARE_MONOTONIC_AND_NON_OVERLAPPING": "ORDERED_NUMERIC_PREDICATE_V1",
    "LOCAL_DETERMINISTIC_RECIPE_OUTPUT_REF_EQUALS_ASSET_REF": "EXACT_EQUALITY_V1"
}

COLLECTION_PROJECTIONS = {
    "CLAIM_IDS_ARE_UNIQUE": ("/claims", "/claims/*/claim_id"),
    "NARRATION_VISUAL_INTENT_IDS_ARE_UNIQUE": ("/sentences", "/sentences/*/visual_intent_id"),
    "MOTION_SEGMENT_IDS_ARE_UNIQUE": ("/shots", "/shots/*/objects/*/motion_segments/*/segment_id"),
}
LOCAL_OUTPUT_BINDING = "LOCAL_DETERMINISTIC_RECIPE_OUTPUT_REF_EQUALS_ASSET_REF"

# Domain declarations for the generic ordered-label interval partition operator.
# Mutation seeds remain independent single edit locations.
PHASE_PARTITION_PROJECTIONS = {
    "ENTER_HOLD_EXIT_SEGMENTS_ARE_CONTIGUOUS_AND_MATCH_DECLARED_INTERVALS": {
        "subject_selector": "/shots/*/objects/*",
        "operand_refs": ["/shots/*/objects/*/motion_segments", "/shots/*/objects/*/enter_time",
                         "/shots/*/objects/*/hold_interval/start_seconds",
                         "/shots/*/objects/*/hold_interval/end_seconds", "/shots/*/objects/*/exit_time"],
        "phases": ["ENTER", "HOLD", "EXIT"],
    },
}

REGISTRY_RESULT_PROJECTIONS = {
    "EVERY_INVARIANT_MUTATION_PRESERVES_JSON_SCHEMA_AND_FAILS_DECLARED_INVARIANT": {
        "case_kind": "INVARIANT", "result_root": "/invariant_negative_case_results",
        "legacy_algorithm": "INVARIANT_COUNTEREXAMPLE_REPLAY_V1"},
    "EVERY_SCHEMA_NATIVE_MUTATION_FAILS_SCHEMA_WITHOUT_ORACLE_OR_SIDE_EFFECTS": {
        "case_kind": "SCHEMA_NATIVE", "result_root": "/schema_native_negative_case_results",
        "legacy_algorithm": "SCHEMA_NATIVE_REJECTION_REPLAY_V1"},
}

# These are semantic dependencies, not permissions inferred from observed test
# failures. Recipe output ref edits can break its byte pair; observed curve edits
# also break the stronger full-object binding. All other failures remain errors.
MUTATION_FAILURE_DEPENDENCIES = {
    LOCAL_OUTPUT_BINDING: ("LOCAL_DETERMINISTIC_ASSET_RECIPE_AND_OUTPUT_ARE_HASH_BOUND",),
    "OBSERVED_MOTION_CURVE_IDS_EQUAL_MOTION_IR_CURVE_IDS": (
        "OBSERVED_MOTION_SEMANTIC_BINDINGS_EQUAL_RENDERED_AND_MOTION_BINDINGS",),
}

# A shared invariant may be consumed by more than one artifact kind. Its
# counterexample dependencies are scoped to that consumer, never unioned
# across unrelated schemas (e.g. Alignment has no shot-union invariant).
MUTATION_FAILURE_DEPENDENCIES_BY_KIND = {
    "FIXTURE_ACCEPTANCE_RECEIPT": {
        "FIXTURE_RESULT_JOB_IDS_EQUAL_FROZEN_REPOSITORY_JOB_IDS": (
            "FIXTURE_RESULT_SOURCE_IDS_EQUAL_FROZEN_REPOSITORY_SOURCE_IDS",),
        "ACCEPTANCE_CASE_RESULT_IDS_EQUAL_FROZEN_ACCEPTANCE_CASE_IDS": (
            "ACCEPTANCE_CASE_RESULT_REFS_EQUAL_FROZEN_CASE_RESULT_REFS",),
        "NEGATIVE_CASE_RESULT_IDS_EQUAL_COMPLETE_NEGATIVE_CASE_IDS": (
            "NEGATIVE_CASE_RESULT_REFS_EQUAL_FROZEN_CASE_RESULT_REFS",
            "NEGATIVE_MUTATION_VARIANT_RESULT_IDS_EQUAL_DECLARED_VARIANT_IDS"),
        "INVARIANT_NEGATIVE_CASE_RESULT_IDS_EQUAL_REGISTRY_CASE_IDS": (
            "EVERY_INVARIANT_RESULT_COVERS_EXACT_APPLICABLE_SCHEMA_SHA256S",
            "EVERY_INVARIANT_MUTATION_PRESERVES_JSON_SCHEMA_AND_FAILS_DECLARED_INVARIANT"),
        "EVERY_INVARIANT_RESULT_COVERS_EXACT_APPLICABLE_SCHEMA_SHA256S": (
            "INVARIANT_NEGATIVE_RESULT_REFS_EQUAL_FROZEN_REGISTRY_RESULT_REFS",
            "EVERY_INVARIANT_MUTATION_PRESERVES_JSON_SCHEMA_AND_FAILS_DECLARED_INVARIANT"),
        "INVARIANT_NEGATIVE_RESULT_REFS_EQUAL_FROZEN_REGISTRY_RESULT_REFS": (
            "EVERY_INVARIANT_MUTATION_PRESERVES_JSON_SCHEMA_AND_FAILS_DECLARED_INVARIANT",),
        "SCHEMA_NATIVE_NEGATIVE_CASE_RESULT_IDS_EQUAL_REGISTRY_CASE_IDS": (
            "SCHEMA_NATIVE_RESULT_REFS_EQUAL_FROZEN_REGISTRY_RESULT_REFS",
            "EVERY_SCHEMA_NATIVE_MUTATION_FAILS_SCHEMA_WITHOUT_ORACLE_OR_SIDE_EFFECTS"),
        "SCHEMA_NATIVE_RESULT_REFS_EQUAL_FROZEN_REGISTRY_RESULT_REFS": (
            "EVERY_SCHEMA_NATIVE_MUTATION_FAILS_SCHEMA_WITHOUT_ORACLE_OR_SIDE_EFFECTS",),
    },
    "OBJECT_MOTION_IR": {
        # The fixed enter-time edit may cross hold_start; it necessarily
        # breaks the unchanged ENTER segment's start boundary. Conversely an
        # enter/hold-order edit can break synchronization. These dependencies
        # follow the fields used by the constraints, not observed test output.
        "EVERY_OBJECT_WORD_TO_MOTION_ERROR_DOES_NOT_EXCEED_0_1_SECONDS": (
            "ENTER_HOLD_EXIT_SEGMENTS_ARE_CONTIGUOUS_AND_MATCH_DECLARED_INTERVALS",
            "ENTER_TIME_LESS_THAN_OR_EQUAL_TO_HOLD_START"),
        "ENTER_TIME_LESS_THAN_OR_EQUAL_TO_HOLD_START": (
            "ENTER_HOLD_EXIT_SEGMENTS_ARE_CONTIGUOUS_AND_MATCH_DECLARED_INTERVALS",
            "EVERY_OBJECT_WORD_TO_MOTION_ERROR_DOES_NOT_EXCEED_0_1_SECONDS"),
        "HOLD_START_LESS_THAN_HOLD_END": (
            "ENTER_HOLD_EXIT_SEGMENTS_ARE_CONTIGUOUS_AND_MATCH_DECLARED_INTERVALS",),
        "HOLD_END_LESS_THAN_OR_EQUAL_TO_EXIT_TIME": (
            "ENTER_HOLD_EXIT_SEGMENTS_ARE_CONTIGUOUS_AND_MATCH_DECLARED_INTERVALS",),
        "SENTENCE_IDS_EQUAL_NARRATION_SCRIPT_SENTENCE_IDS": (
            "SHOT_SENTENCE_ID_UNION_EQUALS_TOP_LEVEL_SENTENCE_IDS",),
        "AUDIO_ANCHOR_IDS_EQUAL_REFERENCED_ALIGNMENT_ANCHOR_IDS": (
            "SHOT_AUDIO_ANCHOR_ID_UNION_EQUALS_TOP_LEVEL_AUDIO_ANCHOR_IDS",),
    },
}


def semantic_projection_errors(invariant_id, contract):
    """Check declared domains independently of the Producer's projection code."""
    from .collection_relations import COLLECTION_RELATIONS, collection_definition_errors
    if invariant_id in COLLECTION_RELATIONS:
        return collection_definition_errors(invariant_id, contract)
    result = REGISTRY_RESULT_PROJECTIONS.get(invariant_id)
    if result is not None:
        refs = [result["result_root"], "/oracle_evaluator_registry_ref"]
        if (contract.get("algorithm") != "REGISTRY_MUTATION_RESULT_EVIDENCE_V1"
                or contract.get("input_refs") != [*refs, EXECUTION_MANIFEST_REF] or contract.get("operand_refs") != refs
                or contract.get("subject_selector") != result["result_root"]
                or contract.get("quantifier") != "SINGLE"
                or contract.get("operand_types") != ["array", "ref"]
                or contract.get("parameters") != {"case_kind": result["case_kind"], "execution_manifest_ref": EXECUTION_MANIFEST_REF, "operand_scopes": ["GLOBAL", "GLOBAL"]}
                or contract.get("branch_selector") != {"mode": "ANY_JSON_SCHEMA_VALID_BRANCH"}):
            return ["INVARIANT_RESULT_EVIDENCE_DOMAIN_INVALID"]
    phase = PHASE_PARTITION_PROJECTIONS.get(invariant_id)
    if phase is not None:
        refs = phase["operand_refs"]
        if (contract.get("algorithm") != "ORDERED_PHASE_INTERVAL_PARTITION_V1"
                or contract.get("subject_selector") != phase["subject_selector"]
                or contract.get("quantifier") != "FOR_ALL"
                or contract.get("input_refs") != refs or contract.get("operand_refs") != refs
                or contract.get("operand_types") != ["array"] + ["scalar"] * (len(refs)-1)
                or contract.get("parameters") != {"phases": phase["phases"], "unit": "seconds",
                                                     "operand_scopes": ["SUBJECT"] * len(refs)}
                or contract.get("branch_selector") != {"mode": "ANY_JSON_SCHEMA_VALID_BRANCH"}):
            return ["INVARIANT_PHASE_PARTITION_DOMAIN_INVALID"]
    projection = COLLECTION_PROJECTIONS.get(invariant_id)
    if projection is not None:
        root, values = projection
        if (contract.get("algorithm") != "CANONICAL_MEMBER_UNIQUENESS_V1"
                or contract.get("subject_selector") != root
                or contract.get("quantifier") != "SINGLE"
                or contract.get("operand_refs") != [values]
                or contract.get("operand_types") != ["array"]
                or contract.get("parameters") != {"operand_scopes": ["GLOBAL"]}
                or contract.get("branch_selector") != {"mode": "ANY_JSON_SCHEMA_VALID_BRANCH"}):
            return ["INVARIANT_COLLECTION_DOMAIN_INVALID"]
    if invariant_id == LOCAL_OUTPUT_BINDING and (
        contract.get("algorithm") != "EXACT_EQUALITY_V1"
        or contract.get("subject_selector") != "/assets/*"
        or contract.get("quantifier") != "FOR_ALL"
        or contract.get("operand_refs") != ["/assets/*/local_build_recipe/output_ref", "/assets/*/asset_ref"]
        or contract.get("operand_types") != ["ref", "ref"]
        or contract.get("branch_selector") != {
            "mode": "REQUIRE_DISCRIMINATOR_IN", "discriminator_ref": "/assets/*/materialization_state",
            "values": ["LOCAL_DETERMINISTIC_VERIFIED"]}
    ):
        return ["INVARIANT_LOCAL_OUTPUT_BINDING_INVALID"]
    return []


def failure_set_schema_errors(schema):
    """The replay obligation requires a representable observed failure set."""
    if "EVERY_INVARIANT_MUTATION_PRESERVES_JSON_SCHEMA_AND_FAILS_DECLARED_INVARIANT" not in schema.get("x-invariants", []):
        return []
    item = schema
    for key in ("properties", "invariant_negative_case_results", "items",
                "properties", "schema_instance_results", "items"):
        item = item.get(key, {}) if isinstance(item, dict) else {}
    fields = item.get("properties", {})
    field = fields.get("failed_invariant_ids", {})
    if ("failed_invariant_ids" not in item.get("required", [])
            or field.get("type") != "array" or field.get("minItems") != 1
            or field.get("uniqueItems") is not True
            or field.get("items", {}).get("type") != "string"
            or field.get("items", {}).get("minLength") != 1):
        return ["INVARIANT_FAILURE_SET_EVIDENCE_MISSING"]
    return []
